// typestemplateinherit.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
// For C users and C++ implementation

#ifndef TYPESTEMPLATEINHERIT_H
#define TYPESTEMPLATEINHERIT_H

// Shared with other Shroud wrapped libraries
#ifndef SHROUD_SHARED_H
#define SHROUD_SHARED_H

enum SwigMemFlags {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};

#endif  // SHROUD_SHARED_H

// splicer begin types.CXX_declarations
// splicer end types.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin types.C_declarations
// splicer end types.C_declarations

// helper capsule_data
struct s_TEM_SHROUD_capsule_data {
    void *addr;     /* address of C++ memory */
    int idtor;      /* index of destructor */
    int cmemflags;  /* memory flags */
};
typedef struct s_TEM_SHROUD_capsule_data TEM_SHROUD_capsule_data;
#if 0

// C++ capsule TEM_BaseMatrix_int
struct s_TEM_BaseMatrix_int {
    BaseMatrix<int> *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_TEM_BaseMatrix_int TEM_BaseMatrix_int;

// C++ capsule TEM_BaseMatrix_double
struct s_TEM_BaseMatrix_double {
    BaseMatrix<double> *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_TEM_BaseMatrix_double TEM_BaseMatrix_double;

// C++ capsule TEM_DerivedMatrix_int
struct s_TEM_DerivedMatrix_int {
    DerivedMatrix<int> *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_TEM_DerivedMatrix_int TEM_DerivedMatrix_int;

// C++ capsule TEM_DerivedMatrix_double
struct s_TEM_DerivedMatrix_double {
    DerivedMatrix<double> *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_TEM_DerivedMatrix_double TEM_DerivedMatrix_double;
#endif

// C capsule TEM_BaseMatrix_int
struct s_TEM_BaseMatrix_int {
    void *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_TEM_BaseMatrix_int TEM_BaseMatrix_int;

// C capsule TEM_BaseMatrix_double
struct s_TEM_BaseMatrix_double {
    void *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_TEM_BaseMatrix_double TEM_BaseMatrix_double;

// C capsule TEM_DerivedMatrix_int
struct s_TEM_DerivedMatrix_int {
    void *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_TEM_DerivedMatrix_int TEM_DerivedMatrix_int;

// C capsule TEM_DerivedMatrix_double
struct s_TEM_DerivedMatrix_double {
    void *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_TEM_DerivedMatrix_double TEM_DerivedMatrix_double;

void TEM_SHROUD_memory_destructor(TEM_SHROUD_capsule_data *cap);

#ifdef __cplusplus
}
#endif

#endif  // TYPESTEMPLATEINHERIT_H
