// utiltemplateinherit.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// typemap
#include "templateinherit.hpp"
// shroud
#include "typestemplateinherit.h"


#ifdef __cplusplus
extern "C" {
#endif

// Release library allocated memory.
void TEM_SHROUD_memory_destructor(TEM_SHROUD_capsule_data *cap)
{
    void *ptr = cap->addr;
    switch (cap->idtor) {
    case 0:   // --none--
    {
        // Nothing to delete
        break;
    }
    case 1:   // BaseMatrix<int>
    {
        BaseMatrix<int> *cxx_ptr =
            reinterpret_cast<BaseMatrix<int> *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 2:   // BaseMatrix<double>
    {
        BaseMatrix<double> *cxx_ptr =
            reinterpret_cast<BaseMatrix<double> *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 3:   // DerivedMatrix<int>
    {
        DerivedMatrix<int> *cxx_ptr =
            reinterpret_cast<DerivedMatrix<int> *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 4:   // DerivedMatrix<double>
    {
        DerivedMatrix<double> *cxx_ptr =
            reinterpret_cast<DerivedMatrix<double> *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 5:   // MixedMatrix<int, double>
    {
        MixedMatrix<int, double> *cxx_ptr =
            reinterpret_cast<MixedMatrix<int, double> *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 6:   // MixedMatrix<double, int>
    {
        MixedMatrix<double, int> *cxx_ptr =
            reinterpret_cast<MixedMatrix<double, int> *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 7:   // ConcreteMatrix<int>
    {
        ConcreteMatrix<int> *cxx_ptr =
            reinterpret_cast<ConcreteMatrix<int> *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 8:   // ConcreteMatrix<double>
    {
        ConcreteMatrix<double> *cxx_ptr =
            reinterpret_cast<ConcreteMatrix<double> *>(ptr);
        delete cxx_ptr;
        break;
    }
    default:
    {
        // Unexpected case in destructor
        break;
    }
    }
    cap->addr = nullptr;
    cap->idtor = 0;  // avoid deleting again
    cap->cmemflags = cap->cmemflags & ~SWIG_MEM_OWN;
}

// Statement: f_operator_assignment_shadow
// BaseMatrix_int = BaseMatrix_int
void TEM_BaseMatrix_int_assign_BaseMatrix_int(TEM_BaseMatrix_int *lhs_capsule,
    TEM_BaseMatrix_int *rhs_capsule)
{
    if (lhs_capsule->addr == nullptr) {
        /* LHS is unassigned */
        if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
            // Capture pointer from RHS, clear 'moving' flag.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = rhs_capsule->idtor;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
        } else {
            // Aliasing another class; clear ownership.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = 0;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
        }
    } else if (rhs_capsule->addr == nullptr) {
        // Replace LHS with a null pointer.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = nullptr;
        lhs_capsule->idtor = 0;
        lhs_capsule->cmemflags = 0;
    } else if (lhs_capsule->addr == rhs_capsule->addr) {
        // Lhs-assignment: ignore.
    } else if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
        // Transferred ownership from a variable that's about to be lost.
        // Move-assign and delete the transient data.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    } else {
        // RHS shouldn't be deleted, alias to LHS.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
}

// Statement: f_operator_assignment_shadow
// BaseMatrix_double = BaseMatrix_double
void TEM_BaseMatrix_double_assign_BaseMatrix_double(TEM_BaseMatrix_double *lhs_capsule,
    TEM_BaseMatrix_double *rhs_capsule)
{
    if (lhs_capsule->addr == nullptr) {
        /* LHS is unassigned */
        if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
            // Capture pointer from RHS, clear 'moving' flag.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = rhs_capsule->idtor;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
        } else {
            // Aliasing another class; clear ownership.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = 0;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
        }
    } else if (rhs_capsule->addr == nullptr) {
        // Replace LHS with a null pointer.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = nullptr;
        lhs_capsule->idtor = 0;
        lhs_capsule->cmemflags = 0;
    } else if (lhs_capsule->addr == rhs_capsule->addr) {
        // Lhs-assignment: ignore.
    } else if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
        // Transferred ownership from a variable that's about to be lost.
        // Move-assign and delete the transient data.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    } else {
        // RHS shouldn't be deleted, alias to LHS.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
}

// Statement: f_operator_assignment_shadow
// DerivedMatrix_int = DerivedMatrix_int
void TEM_DerivedMatrix_int_assign_DerivedMatrix_int(TEM_DerivedMatrix_int *lhs_capsule,
    TEM_DerivedMatrix_int *rhs_capsule)
{
    if (lhs_capsule->addr == nullptr) {
        /* LHS is unassigned */
        if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
            // Capture pointer from RHS, clear 'moving' flag.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = rhs_capsule->idtor;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
        } else {
            // Aliasing another class; clear ownership.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = 0;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
        }
    } else if (rhs_capsule->addr == nullptr) {
        // Replace LHS with a null pointer.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = nullptr;
        lhs_capsule->idtor = 0;
        lhs_capsule->cmemflags = 0;
    } else if (lhs_capsule->addr == rhs_capsule->addr) {
        // Lhs-assignment: ignore.
    } else if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
        // Transferred ownership from a variable that's about to be lost.
        // Move-assign and delete the transient data.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    } else {
        // RHS shouldn't be deleted, alias to LHS.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
}

// Statement: f_operator_assignment_shadow
// DerivedMatrix_double = DerivedMatrix_double
void TEM_DerivedMatrix_double_assign_DerivedMatrix_double(TEM_DerivedMatrix_double *lhs_capsule,
    TEM_DerivedMatrix_double *rhs_capsule)
{
    if (lhs_capsule->addr == nullptr) {
        /* LHS is unassigned */
        if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
            // Capture pointer from RHS, clear 'moving' flag.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = rhs_capsule->idtor;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
        } else {
            // Aliasing another class; clear ownership.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = 0;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
        }
    } else if (rhs_capsule->addr == nullptr) {
        // Replace LHS with a null pointer.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = nullptr;
        lhs_capsule->idtor = 0;
        lhs_capsule->cmemflags = 0;
    } else if (lhs_capsule->addr == rhs_capsule->addr) {
        // Lhs-assignment: ignore.
    } else if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
        // Transferred ownership from a variable that's about to be lost.
        // Move-assign and delete the transient data.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    } else {
        // RHS shouldn't be deleted, alias to LHS.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
}

// Statement: f_operator_assignment_shadow
// MixedMatrix_int_double = MixedMatrix_int_double
void TEM_MixedMatrix_int_double_assign_MixedMatrix_int_double(TEM_MixedMatrix_int_double *lhs_capsule,
    TEM_MixedMatrix_int_double *rhs_capsule)
{
    if (lhs_capsule->addr == nullptr) {
        /* LHS is unassigned */
        if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
            // Capture pointer from RHS, clear 'moving' flag.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = rhs_capsule->idtor;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
        } else {
            // Aliasing another class; clear ownership.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = 0;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
        }
    } else if (rhs_capsule->addr == nullptr) {
        // Replace LHS with a null pointer.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = nullptr;
        lhs_capsule->idtor = 0;
        lhs_capsule->cmemflags = 0;
    } else if (lhs_capsule->addr == rhs_capsule->addr) {
        // Lhs-assignment: ignore.
    } else if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
        // Transferred ownership from a variable that's about to be lost.
        // Move-assign and delete the transient data.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    } else {
        // RHS shouldn't be deleted, alias to LHS.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
}

// Statement: f_operator_assignment_shadow
// MixedMatrix_double_int = MixedMatrix_double_int
void TEM_MixedMatrix_double_int_assign_MixedMatrix_double_int(TEM_MixedMatrix_double_int *lhs_capsule,
    TEM_MixedMatrix_double_int *rhs_capsule)
{
    if (lhs_capsule->addr == nullptr) {
        /* LHS is unassigned */
        if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
            // Capture pointer from RHS, clear 'moving' flag.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = rhs_capsule->idtor;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
        } else {
            // Aliasing another class; clear ownership.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = 0;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
        }
    } else if (rhs_capsule->addr == nullptr) {
        // Replace LHS with a null pointer.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = nullptr;
        lhs_capsule->idtor = 0;
        lhs_capsule->cmemflags = 0;
    } else if (lhs_capsule->addr == rhs_capsule->addr) {
        // Lhs-assignment: ignore.
    } else if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
        // Transferred ownership from a variable that's about to be lost.
        // Move-assign and delete the transient data.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    } else {
        // RHS shouldn't be deleted, alias to LHS.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
}

// Statement: f_operator_assignment_shadow
// ConcreteMatrix_int = ConcreteMatrix_int
void TEM_ConcreteMatrix_int_assign_ConcreteMatrix_int(TEM_ConcreteMatrix_int *lhs_capsule,
    TEM_ConcreteMatrix_int *rhs_capsule)
{
    if (lhs_capsule->addr == nullptr) {
        /* LHS is unassigned */
        if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
            // Capture pointer from RHS, clear 'moving' flag.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = rhs_capsule->idtor;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
        } else {
            // Aliasing another class; clear ownership.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = 0;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
        }
    } else if (rhs_capsule->addr == nullptr) {
        // Replace LHS with a null pointer.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = nullptr;
        lhs_capsule->idtor = 0;
        lhs_capsule->cmemflags = 0;
    } else if (lhs_capsule->addr == rhs_capsule->addr) {
        // Lhs-assignment: ignore.
    } else if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
        // Transferred ownership from a variable that's about to be lost.
        // Move-assign and delete the transient data.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    } else {
        // RHS shouldn't be deleted, alias to LHS.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
}

// Statement: f_operator_assignment_shadow
// ConcreteMatrix_double = ConcreteMatrix_double
void TEM_ConcreteMatrix_double_assign_ConcreteMatrix_double(TEM_ConcreteMatrix_double *lhs_capsule,
    TEM_ConcreteMatrix_double *rhs_capsule)
{
    if (lhs_capsule->addr == nullptr) {
        /* LHS is unassigned */
        if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
            // Capture pointer from RHS, clear 'moving' flag.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = rhs_capsule->idtor;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
        } else {
            // Aliasing another class; clear ownership.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = 0;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
        }
    } else if (rhs_capsule->addr == nullptr) {
        // Replace LHS with a null pointer.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = nullptr;
        lhs_capsule->idtor = 0;
        lhs_capsule->cmemflags = 0;
    } else if (lhs_capsule->addr == rhs_capsule->addr) {
        // Lhs-assignment: ignore.
    } else if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
        // Transferred ownership from a variable that's about to be lost.
        // Move-assign and delete the transient data.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    } else {
        // RHS shouldn't be deleted, alias to LHS.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            TEM_SHROUD_memory_destructor(
                (TEM_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
}

#ifdef __cplusplus
}
#endif
