// wrapMixedMatrix_int_double.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapMixedMatrix_int_double.h
 * \brief Shroud generated wrapper for MixedMatrix class
 */
// For C users and C++ implementation

#ifndef WRAPMIXEDMATRIX_INT_DOUBLE_H
#define WRAPMIXEDMATRIX_INT_DOUBLE_H

// shroud
#include "typestemplateinherit.h"

// splicer begin class.MixedMatrix.CXX_declarations
// splicer end class.MixedMatrix.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.MixedMatrix.C_declarations
// splicer end class.MixedMatrix.C_declarations

TEM_MixedMatrix_int_double * TEM_MixedMatrix_int_double_ctor(
    TEM_MixedMatrix_int_double *SHC_rv);

void TEM_MixedMatrix_int_double_ctor_bufferify(
    TEM_MixedMatrix_int_double *SHC_rv);

double TEM_MixedMatrix_int_double_get_mixed(
    TEM_MixedMatrix_int_double * self);

void TEM_MixedMatrix_int_double_convert_int(
    TEM_MixedMatrix_int_double * self, int value);

void TEM_MixedMatrix_int_double_convert_double(
    TEM_MixedMatrix_int_double * self, double value);

#ifdef __cplusplus
}
#endif

#endif  // WRAPMIXEDMATRIX_INT_DOUBLE_H
