// wrapBaseMatrix_int.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// cxx_header
#include "templateinherit.hpp"
// shroud
#include "wrapBaseMatrix_int.h"

// splicer begin class.BaseMatrix.CXX_definitions
// splicer end class.BaseMatrix.CXX_definitions

extern "C" {

// splicer begin class.BaseMatrix.C_definitions
// splicer end class.BaseMatrix.C_definitions

// ----------------------------------------
// Function:  BaseMatrix
// Statement: c_ctor_shadow_capptr
TEM_BaseMatrix_int * TEM_BaseMatrix_int_ctor(TEM_BaseMatrix_int *SHC_rv)
{
    // splicer begin class.BaseMatrix.method.ctor
    BaseMatrix<int> *SHCXX_rv = new BaseMatrix<int>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 1;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    return SHC_rv;
    // splicer end class.BaseMatrix.method.ctor
}

// ----------------------------------------
// Function:  BaseMatrix
// Statement: f_ctor_shadow_capsule_caller
void TEM_BaseMatrix_int_ctor_bufferify(TEM_BaseMatrix_int *SHC_rv)
{
    // splicer begin class.BaseMatrix.method.ctor_bufferify
    BaseMatrix<int> *SHCXX_rv = new BaseMatrix<int>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 1;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    // splicer end class.BaseMatrix.method.ctor_bufferify
}

// Generated by cxx_template
// ----------------------------------------
// Function:  void set_base
// Statement: c_subroutine
// ----------------------------------------
// Argument:  int v
// Statement: c_in_native
void TEM_BaseMatrix_int_set_base(TEM_BaseMatrix_int * self, int v)
{
    BaseMatrix<int> *SH_this = static_cast<BaseMatrix<int> *>
        (self->addr);
    // splicer begin class.BaseMatrix.method.set_base
    SH_this->set_base(v);
    // splicer end class.BaseMatrix.method.set_base
}

}  // extern "C"
