// wrapMixedMatrix_double_int.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// cxx_header
#include "templateinherit.hpp"
// shroud
#include "wrapMixedMatrix_double_int.h"

// splicer begin class.MixedMatrix.CXX_definitions
// splicer end class.MixedMatrix.CXX_definitions

extern "C" {

// splicer begin class.MixedMatrix.C_definitions
// splicer end class.MixedMatrix.C_definitions

// ----------------------------------------
// Function:  MixedMatrix
// Statement: c_ctor_shadow_capptr
TEM_MixedMatrix_double_int * TEM_MixedMatrix_double_int_ctor(
    TEM_MixedMatrix_double_int *SHC_rv)
{
    // splicer begin class.MixedMatrix.method.ctor
    MixedMatrix<double, int> *SHCXX_rv = new MixedMatrix<double, int>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 6;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    return SHC_rv;
    // splicer end class.MixedMatrix.method.ctor
}

// ----------------------------------------
// Function:  MixedMatrix
// Statement: f_ctor_shadow_capsule_caller
void TEM_MixedMatrix_double_int_ctor_bufferify(
    TEM_MixedMatrix_double_int *SHC_rv)
{
    // splicer begin class.MixedMatrix.method.ctor_bufferify
    MixedMatrix<double, int> *SHCXX_rv = new MixedMatrix<double, int>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 6;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    // splicer end class.MixedMatrix.method.ctor_bufferify
}

// Generated by cxx_template
// ----------------------------------------
// Function:  void set_mixed
// Statement: c_subroutine
// ----------------------------------------
// Argument:  double v
// Statement: c_in_native
// ----------------------------------------
// Argument:  int w
// Statement: c_in_native
void TEM_MixedMatrix_double_int_set_mixed(
    TEM_MixedMatrix_double_int * self, double v, int w)
{
    MixedMatrix<double, int> *SH_this =
        static_cast<MixedMatrix<double, int> *>(self->addr);
    // splicer begin class.MixedMatrix.method.set_mixed
    SH_this->set_mixed(v, w);
    // splicer end class.MixedMatrix.method.set_mixed
}

// Generated by cxx_template
// ----------------------------------------
// Function:  int get_mixed
// Statement: c_function_native
int TEM_MixedMatrix_double_int_get_mixed(
    TEM_MixedMatrix_double_int * self)
{
    MixedMatrix<double, int> *SH_this =
        static_cast<MixedMatrix<double, int> *>(self->addr);
    // splicer begin class.MixedMatrix.method.get_mixed
    int SHC_rv = SH_this->get_mixed();
    return SHC_rv;
    // splicer end class.MixedMatrix.method.get_mixed
}

}  // extern "C"
