// wrapBaseMatrix_int.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapBaseMatrix_int.h
 * \brief Shroud generated wrapper for BaseMatrix class
 */
// For C users and C++ implementation

#ifndef WRAPBASEMATRIX_INT_H
#define WRAPBASEMATRIX_INT_H

// shroud
#include "typestemplateinherit.h"

// splicer begin class.BaseMatrix.CXX_declarations
// splicer end class.BaseMatrix.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.BaseMatrix.C_declarations
// splicer end class.BaseMatrix.C_declarations

TEM_BaseMatrix_int * TEM_BaseMatrix_int_ctor(
    TEM_BaseMatrix_int *SHC_rv);

void TEM_BaseMatrix_int_ctor_bufferify(TEM_BaseMatrix_int *SHC_rv);

void TEM_BaseMatrix_int_set_base(TEM_BaseMatrix_int * self, int v);

#ifdef __cplusplus
}
#endif

#endif  // WRAPBASEMATRIX_INT_H
