! wrapftemplateinherit.f
! This file is generated by Shroud nowrite-version. Do not edit.
! Copyright Shroud Project Developers. See LICENSE file for details.
!
! SPDX-License-Identifier: (BSD-3-Clause)
!
!>
!! \file wrapftemplateinherit.f
!! \brief Shroud generated wrapper for templateinherit library
!<
! splicer begin file_top
! splicer end file_top
module templateinherit_mod
    use iso_c_binding, only : C_INT, C_NULL_PTR, C_PTR
    ! splicer begin module_use
    ! splicer end module_use
    implicit none

    ! splicer begin module_top
    ! splicer end module_top

    ! helper capsule_data
    type, bind(C) :: TEM_SHROUD_capsule_data
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
        integer(C_INT) :: cmemflags = 0   ! memory flags
    end type TEM_SHROUD_capsule_data

    type base_matrix_int
        type(TEM_SHROUD_capsule_data) :: cxxmem = &
            TEM_SHROUD_capsule_data()
        ! splicer begin class.BaseMatrix_int.component_part
        ! splicer end class.BaseMatrix_int.component_part
    contains
        procedure :: set_base => base_matrix_int_set_base
        procedure :: get_instance => base_matrix_int_get_instance
        procedure :: set_instance => base_matrix_int_set_instance
        procedure :: associated => base_matrix_int_associated
        ! splicer begin class.BaseMatrix_int.type_bound_procedure_part
        ! splicer end class.BaseMatrix_int.type_bound_procedure_part
    end type base_matrix_int

    type base_matrix_double
        type(TEM_SHROUD_capsule_data) :: cxxmem = &
            TEM_SHROUD_capsule_data()
        ! splicer begin class.BaseMatrix_double.component_part
        ! splicer end class.BaseMatrix_double.component_part
    contains
        procedure :: set_base => base_matrix_double_set_base
        procedure :: get_base => base_matrix_double_get_base
        procedure :: get_instance => base_matrix_double_get_instance
        procedure :: set_instance => base_matrix_double_set_instance
        procedure :: associated => base_matrix_double_associated
        ! splicer begin class.BaseMatrix_double.type_bound_procedure_part
        ! splicer end class.BaseMatrix_double.type_bound_procedure_part
    end type base_matrix_double

    type, extends(base_matrix_int) :: derived_matrix_int
        ! splicer begin class.DerivedMatrix_int.component_part
        ! splicer end class.DerivedMatrix_int.component_part
    contains
        procedure :: set_derived => derived_matrix_int_set_derived
        procedure :: get_derived => derived_matrix_int_get_derived
        ! splicer begin class.DerivedMatrix_int.type_bound_procedure_part
        ! splicer end class.DerivedMatrix_int.type_bound_procedure_part
    end type derived_matrix_int

    type, extends(base_matrix_double) :: derived_matrix_double
        ! splicer begin class.DerivedMatrix_double.component_part
        ! splicer end class.DerivedMatrix_double.component_part
    contains
        procedure :: set_derived => derived_matrix_double_set_derived
        procedure :: get_derived => derived_matrix_double_get_derived
        ! splicer begin class.DerivedMatrix_double.type_bound_procedure_part
        ! splicer end class.DerivedMatrix_double.type_bound_procedure_part
    end type derived_matrix_double

    type, extends(base_matrix_int) :: mixed_matrix_int_double
        ! splicer begin class.MixedMatrix_int_double.component_part
        ! splicer end class.MixedMatrix_int_double.component_part
    contains
        procedure :: get_mixed => mixed_matrix_int_double_get_mixed
        procedure :: convert_int => mixed_matrix_int_double_convert_int
        procedure :: convert_double => mixed_matrix_int_double_convert_double
        generic :: convert => convert_int, convert_double
        ! splicer begin class.MixedMatrix_int_double.type_bound_procedure_part
        ! splicer end class.MixedMatrix_int_double.type_bound_procedure_part
    end type mixed_matrix_int_double

    type, extends(base_matrix_double) :: mixed_matrix_double_int
        ! splicer begin class.MixedMatrix_double_int.component_part
        ! splicer end class.MixedMatrix_double_int.component_part
    contains
        procedure :: set_mixed => mixed_matrix_double_int_set_mixed
        procedure :: get_mixed => mixed_matrix_double_int_get_mixed
        ! splicer begin class.MixedMatrix_double_int.type_bound_procedure_part
        ! splicer end class.MixedMatrix_double_int.type_bound_procedure_part
    end type mixed_matrix_double_int

    type, extends(base_matrix_double) :: concrete_matrix_int
        ! splicer begin class.ConcreteMatrix_int.component_part
        ! splicer end class.ConcreteMatrix_int.component_part
    contains
        procedure :: set_concrete => concrete_matrix_int_set_concrete
        ! splicer begin class.ConcreteMatrix_int.type_bound_procedure_part
        ! splicer end class.ConcreteMatrix_int.type_bound_procedure_part
    end type concrete_matrix_int

    type, extends(base_matrix_double) :: concrete_matrix_double
        ! splicer begin class.ConcreteMatrix_double.component_part
        ! splicer end class.ConcreteMatrix_double.component_part
    contains
        procedure :: set_concrete => concrete_matrix_double_set_concrete
        ! splicer begin class.ConcreteMatrix_double.type_bound_procedure_part
        ! splicer end class.ConcreteMatrix_double.type_bound_procedure_part
    end type concrete_matrix_double

    interface operator (.eq.)
        module procedure base_matrix_int_eq
        module procedure base_matrix_double_eq
        module procedure derived_matrix_int_eq
        module procedure derived_matrix_double_eq
        module procedure mixed_matrix_int_double_eq
        module procedure mixed_matrix_double_int_eq
        module procedure concrete_matrix_int_eq
        module procedure concrete_matrix_double_eq
    end interface

    interface operator (.ne.)
        module procedure base_matrix_int_ne
        module procedure base_matrix_double_ne
        module procedure derived_matrix_int_ne
        module procedure derived_matrix_double_ne
        module procedure mixed_matrix_int_double_ne
        module procedure mixed_matrix_double_int_ne
        module procedure concrete_matrix_int_ne
        module procedure concrete_matrix_double_ne
    end interface

    interface assignment (=)
        module procedure base_matrix_int_assign_BaseMatrix_int
        module procedure base_matrix_double_assign_BaseMatrix_double
        module procedure derived_matrix_int_assign_DerivedMatrix_int
        module procedure derived_matrix_double_assign_DerivedMatrix_double
        module procedure mixed_matrix_int_double_assign_MixedMatrix_int_double
        module procedure mixed_matrix_double_int_assign_MixedMatrix_double_int
        module procedure concrete_matrix_int_assign_ConcreteMatrix_int
        module procedure concrete_matrix_double_assign_ConcreteMatrix_double
    end interface

    interface

        ! ----------------------------------------
        ! Function:  BaseMatrix
        ! Statement: c_ctor_shadow_capptr
        function c_base_matrix_int_ctor(SHT_rv) &
                result(SHT_rv_ptr) &
                bind(C, name="TEM_BaseMatrix_int_ctor")
            use iso_c_binding, only : C_PTR
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
            type(C_PTR) :: SHT_rv_ptr
        end function c_base_matrix_int_ctor

        ! ----------------------------------------
        ! Function:  BaseMatrix
        ! Statement: f_ctor_shadow_capsule_caller
        subroutine c_base_matrix_int_ctor_bufferify(SHT_rv) &
                bind(C, name="TEM_BaseMatrix_int_ctor_bufferify")
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
        end subroutine c_base_matrix_int_ctor_bufferify

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void set_base
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  int v
        ! Statement: f_in_native
        subroutine c_base_matrix_int_set_base(self, v) &
                bind(C, name="TEM_BaseMatrix_int_set_base")
            use iso_c_binding, only : C_INT
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: v
        end subroutine c_base_matrix_int_set_base

        ! ----------------------------------------
        ! Function:  BaseMatrix
        ! Statement: c_ctor_shadow_capptr
        function c_base_matrix_double_ctor(SHT_rv) &
                result(SHT_rv_ptr) &
                bind(C, name="TEM_BaseMatrix_double_ctor")
            use iso_c_binding, only : C_PTR
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
            type(C_PTR) :: SHT_rv_ptr
        end function c_base_matrix_double_ctor

        ! ----------------------------------------
        ! Function:  BaseMatrix
        ! Statement: f_ctor_shadow_capsule_caller
        subroutine c_base_matrix_double_ctor_bufferify(SHT_rv) &
                bind(C, name="TEM_BaseMatrix_double_ctor_bufferify")
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
        end subroutine c_base_matrix_double_ctor_bufferify

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void set_base
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  double v
        ! Statement: f_in_native
        subroutine c_base_matrix_double_set_base(self, v) &
                bind(C, name="TEM_BaseMatrix_double_set_base")
            use iso_c_binding, only : C_DOUBLE
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            real(C_DOUBLE), value, intent(IN) :: v
        end subroutine c_base_matrix_double_set_base

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  double get_base
        ! Statement: f_function_native
        function c_base_matrix_double_get_base(self) &
                result(SHT_rv) &
                bind(C, name="TEM_BaseMatrix_double_get_base")
            use iso_c_binding, only : C_DOUBLE
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            real(C_DOUBLE) :: SHT_rv
        end function c_base_matrix_double_get_base

        ! ----------------------------------------
        ! Function:  DerivedMatrix
        ! Statement: c_ctor_shadow_capptr
        function c_derived_matrix_int_ctor(SHT_rv) &
                result(SHT_rv_ptr) &
                bind(C, name="TEM_DerivedMatrix_int_ctor")
            use iso_c_binding, only : C_PTR
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
            type(C_PTR) :: SHT_rv_ptr
        end function c_derived_matrix_int_ctor

        ! ----------------------------------------
        ! Function:  DerivedMatrix
        ! Statement: f_ctor_shadow_capsule_caller
        subroutine c_derived_matrix_int_ctor_bufferify(SHT_rv) &
                bind(C, name="TEM_DerivedMatrix_int_ctor_bufferify")
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
        end subroutine c_derived_matrix_int_ctor_bufferify

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void set_derived
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  int v
        ! Statement: f_in_native
        subroutine c_derived_matrix_int_set_derived(self, v) &
                bind(C, name="TEM_DerivedMatrix_int_set_derived")
            use iso_c_binding, only : C_INT
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: v
        end subroutine c_derived_matrix_int_set_derived

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  int get_derived
        ! Statement: f_function_native
        function c_derived_matrix_int_get_derived(self) &
                result(SHT_rv) &
                bind(C, name="TEM_DerivedMatrix_int_get_derived")
            use iso_c_binding, only : C_INT
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            integer(C_INT) :: SHT_rv
        end function c_derived_matrix_int_get_derived

        ! ----------------------------------------
        ! Function:  DerivedMatrix
        ! Statement: c_ctor_shadow_capptr
        function c_derived_matrix_double_ctor(SHT_rv) &
                result(SHT_rv_ptr) &
                bind(C, name="TEM_DerivedMatrix_double_ctor")
            use iso_c_binding, only : C_PTR
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
            type(C_PTR) :: SHT_rv_ptr
        end function c_derived_matrix_double_ctor

        ! ----------------------------------------
        ! Function:  DerivedMatrix
        ! Statement: f_ctor_shadow_capsule_caller
        subroutine c_derived_matrix_double_ctor_bufferify(SHT_rv) &
                bind(C, name="TEM_DerivedMatrix_double_ctor_bufferify")
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
        end subroutine c_derived_matrix_double_ctor_bufferify

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void set_derived
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  double v
        ! Statement: f_in_native
        subroutine c_derived_matrix_double_set_derived(self, v) &
                bind(C, name="TEM_DerivedMatrix_double_set_derived")
            use iso_c_binding, only : C_DOUBLE
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            real(C_DOUBLE), value, intent(IN) :: v
        end subroutine c_derived_matrix_double_set_derived

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  double get_derived
        ! Statement: f_function_native
        function c_derived_matrix_double_get_derived(self) &
                result(SHT_rv) &
                bind(C, name="TEM_DerivedMatrix_double_get_derived")
            use iso_c_binding, only : C_DOUBLE
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            real(C_DOUBLE) :: SHT_rv
        end function c_derived_matrix_double_get_derived

        ! ----------------------------------------
        ! Function:  MixedMatrix
        ! Statement: c_ctor_shadow_capptr
        function c_mixed_matrix_int_double_ctor(SHT_rv) &
                result(SHT_rv_ptr) &
                bind(C, name="TEM_MixedMatrix_int_double_ctor")
            use iso_c_binding, only : C_PTR
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
            type(C_PTR) :: SHT_rv_ptr
        end function c_mixed_matrix_int_double_ctor

        ! ----------------------------------------
        ! Function:  MixedMatrix
        ! Statement: f_ctor_shadow_capsule_caller
        subroutine c_mixed_matrix_int_double_ctor_bufferify(SHT_rv) &
                bind(C, name="TEM_MixedMatrix_int_double_ctor_bufferify")
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
        end subroutine c_mixed_matrix_int_double_ctor_bufferify

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  double get_mixed
        ! Statement: f_function_native
        function c_mixed_matrix_int_double_get_mixed(self) &
                result(SHT_rv) &
                bind(C, name="TEM_MixedMatrix_int_double_get_mixed")
            use iso_c_binding, only : C_DOUBLE
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            real(C_DOUBLE) :: SHT_rv
        end function c_mixed_matrix_int_double_get_mixed

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void convert
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  int value
        ! Statement: f_in_native
        subroutine c_mixed_matrix_int_double_convert_int(self, value) &
                bind(C, name="TEM_MixedMatrix_int_double_convert_int")
            use iso_c_binding, only : C_INT
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: value
        end subroutine c_mixed_matrix_int_double_convert_int

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void convert
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  double value
        ! Statement: f_in_native
        subroutine c_mixed_matrix_int_double_convert_double(self, value) &
                bind(C, name="TEM_MixedMatrix_int_double_convert_double")
            use iso_c_binding, only : C_DOUBLE
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            real(C_DOUBLE), value, intent(IN) :: value
        end subroutine c_mixed_matrix_int_double_convert_double

        ! ----------------------------------------
        ! Function:  MixedMatrix
        ! Statement: c_ctor_shadow_capptr
        function c_mixed_matrix_double_int_ctor(SHT_rv) &
                result(SHT_rv_ptr) &
                bind(C, name="TEM_MixedMatrix_double_int_ctor")
            use iso_c_binding, only : C_PTR
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
            type(C_PTR) :: SHT_rv_ptr
        end function c_mixed_matrix_double_int_ctor

        ! ----------------------------------------
        ! Function:  MixedMatrix
        ! Statement: f_ctor_shadow_capsule_caller
        subroutine c_mixed_matrix_double_int_ctor_bufferify(SHT_rv) &
                bind(C, name="TEM_MixedMatrix_double_int_ctor_bufferify")
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
        end subroutine c_mixed_matrix_double_int_ctor_bufferify

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void set_mixed
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  double v
        ! Statement: f_in_native
        ! ----------------------------------------
        ! Argument:  int w
        ! Statement: f_in_native
        subroutine c_mixed_matrix_double_int_set_mixed(self, v, w) &
                bind(C, name="TEM_MixedMatrix_double_int_set_mixed")
            use iso_c_binding, only : C_DOUBLE, C_INT
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            real(C_DOUBLE), value, intent(IN) :: v
            integer(C_INT), value, intent(IN) :: w
        end subroutine c_mixed_matrix_double_int_set_mixed

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  int get_mixed
        ! Statement: f_function_native
        function c_mixed_matrix_double_int_get_mixed(self) &
                result(SHT_rv) &
                bind(C, name="TEM_MixedMatrix_double_int_get_mixed")
            use iso_c_binding, only : C_INT
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            integer(C_INT) :: SHT_rv
        end function c_mixed_matrix_double_int_get_mixed

        ! ----------------------------------------
        ! Function:  ConcreteMatrix
        ! Statement: c_ctor_shadow_capptr
        function c_concrete_matrix_int_ctor(SHT_rv) &
                result(SHT_rv_ptr) &
                bind(C, name="TEM_ConcreteMatrix_int_ctor")
            use iso_c_binding, only : C_PTR
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
            type(C_PTR) :: SHT_rv_ptr
        end function c_concrete_matrix_int_ctor

        ! ----------------------------------------
        ! Function:  ConcreteMatrix
        ! Statement: f_ctor_shadow_capsule_caller
        subroutine c_concrete_matrix_int_ctor_bufferify(SHT_rv) &
                bind(C, name="TEM_ConcreteMatrix_int_ctor_bufferify")
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
        end subroutine c_concrete_matrix_int_ctor_bufferify

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void set_concrete
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  int v
        ! Statement: f_in_native
        subroutine c_concrete_matrix_int_set_concrete(self, v) &
                bind(C, name="TEM_ConcreteMatrix_int_set_concrete")
            use iso_c_binding, only : C_INT
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: v
        end subroutine c_concrete_matrix_int_set_concrete

        ! ----------------------------------------
        ! Function:  ConcreteMatrix
        ! Statement: c_ctor_shadow_capptr
        function c_concrete_matrix_double_ctor(SHT_rv) &
                result(SHT_rv_ptr) &
                bind(C, name="TEM_ConcreteMatrix_double_ctor")
            use iso_c_binding, only : C_PTR
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
            type(C_PTR) :: SHT_rv_ptr
        end function c_concrete_matrix_double_ctor

        ! ----------------------------------------
        ! Function:  ConcreteMatrix
        ! Statement: f_ctor_shadow_capsule_caller
        subroutine c_concrete_matrix_double_ctor_bufferify(SHT_rv) &
                bind(C, name="TEM_ConcreteMatrix_double_ctor_bufferify")
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(OUT) :: SHT_rv
        end subroutine c_concrete_matrix_double_ctor_bufferify

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void set_concrete
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  double v
        ! Statement: f_in_native
        subroutine c_concrete_matrix_double_set_concrete(self, v) &
                bind(C, name="TEM_ConcreteMatrix_double_set_concrete")
            use iso_c_binding, only : C_DOUBLE
            import :: TEM_SHROUD_capsule_data
            implicit none
            type(TEM_SHROUD_capsule_data), intent(IN) :: self
            real(C_DOUBLE), value, intent(IN) :: v
        end subroutine c_concrete_matrix_double_set_concrete
    end interface

    interface base_matrix_double
        module procedure base_matrix_double_ctor
    end interface base_matrix_double

    interface base_matrix_int
        module procedure base_matrix_int_ctor
    end interface base_matrix_int

    interface concrete_matrix_double
        module procedure concrete_matrix_double_ctor
    end interface concrete_matrix_double

    interface concrete_matrix_int
        module procedure concrete_matrix_int_ctor
    end interface concrete_matrix_int

    interface derived_matrix_double
        module procedure derived_matrix_double_ctor
    end interface derived_matrix_double

    interface derived_matrix_int
        module procedure derived_matrix_int_ctor
    end interface derived_matrix_int

    interface mixed_matrix_double_int
        module procedure mixed_matrix_double_int_ctor
    end interface mixed_matrix_double_int

    interface mixed_matrix_int_double
        module procedure mixed_matrix_int_double_ctor
    end interface mixed_matrix_int_double

    interface mixed_matrix_int_double_convert
        module procedure mixed_matrix_int_double_convert_int
        module procedure mixed_matrix_int_double_convert_double
    end interface mixed_matrix_int_double_convert

    ! splicer begin additional_declarations
    ! splicer end additional_declarations

contains

    ! ----------------------------------------
    ! Function:  BaseMatrix
    ! Statement: f_ctor_shadow_capsule_caller
    function base_matrix_int_ctor() &
            result(SHT_rv)
        type(base_matrix_int) :: SHT_rv
        ! splicer begin class.BaseMatrix_int.method.ctor
        call c_base_matrix_int_ctor_bufferify(SHT_rv%cxxmem)
        ! splicer end class.BaseMatrix_int.method.ctor
    end function base_matrix_int_ctor

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void set_base
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  int v
    ! Statement: f_in_native
    subroutine base_matrix_int_set_base(obj, v)
        use iso_c_binding, only : C_INT
        class(base_matrix_int), intent(INOUT) :: obj
        integer(C_INT), value, intent(IN) :: v
        ! splicer begin class.BaseMatrix_int.method.set_base
        call c_base_matrix_int_set_base(obj%cxxmem, v)
        ! splicer end class.BaseMatrix_int.method.set_base
    end subroutine base_matrix_int_set_base

    ! Return pointer to C++ memory.
    function base_matrix_int_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(base_matrix_int), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function base_matrix_int_get_instance

    subroutine base_matrix_int_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(base_matrix_int), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine base_matrix_int_set_instance

    function base_matrix_int_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(base_matrix_int), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function base_matrix_int_associated

    ! splicer begin class.BaseMatrix_int.additional_functions
    ! splicer end class.BaseMatrix_int.additional_functions

    ! ----------------------------------------
    ! Function:  BaseMatrix
    ! Statement: f_ctor_shadow_capsule_caller
    function base_matrix_double_ctor() &
            result(SHT_rv)
        type(base_matrix_double) :: SHT_rv
        ! splicer begin class.BaseMatrix_double.method.ctor
        call c_base_matrix_double_ctor_bufferify(SHT_rv%cxxmem)
        ! splicer end class.BaseMatrix_double.method.ctor
    end function base_matrix_double_ctor

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void set_base
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  double v
    ! Statement: f_in_native
    subroutine base_matrix_double_set_base(obj, v)
        use iso_c_binding, only : C_DOUBLE
        class(base_matrix_double), intent(INOUT) :: obj
        real(C_DOUBLE), value, intent(IN) :: v
        ! splicer begin class.BaseMatrix_double.method.set_base
        call c_base_matrix_double_set_base(obj%cxxmem, v)
        ! splicer end class.BaseMatrix_double.method.set_base
    end subroutine base_matrix_double_set_base

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  double get_base
    ! Statement: f_function_native
    function base_matrix_double_get_base(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_DOUBLE
        class(base_matrix_double), intent(INOUT) :: obj
        real(C_DOUBLE) :: SHT_rv
        ! splicer begin class.BaseMatrix_double.method.get_base
        SHT_rv = c_base_matrix_double_get_base(obj%cxxmem)
        ! splicer end class.BaseMatrix_double.method.get_base
    end function base_matrix_double_get_base

    ! Return pointer to C++ memory.
    function base_matrix_double_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(base_matrix_double), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function base_matrix_double_get_instance

    subroutine base_matrix_double_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(base_matrix_double), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine base_matrix_double_set_instance

    function base_matrix_double_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(base_matrix_double), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function base_matrix_double_associated

    ! splicer begin class.BaseMatrix_double.additional_functions
    ! splicer end class.BaseMatrix_double.additional_functions

    ! ----------------------------------------
    ! Function:  DerivedMatrix
    ! Statement: f_ctor_shadow_capsule_caller
    function derived_matrix_int_ctor() &
            result(SHT_rv)
        type(derived_matrix_int) :: SHT_rv
        ! splicer begin class.DerivedMatrix_int.method.ctor
        call c_derived_matrix_int_ctor_bufferify(SHT_rv%cxxmem)
        ! splicer end class.DerivedMatrix_int.method.ctor
    end function derived_matrix_int_ctor

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void set_derived
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  int v
    ! Statement: f_in_native
    subroutine derived_matrix_int_set_derived(obj, v)
        use iso_c_binding, only : C_INT
        class(derived_matrix_int), intent(INOUT) :: obj
        integer(C_INT), value, intent(IN) :: v
        ! splicer begin class.DerivedMatrix_int.method.set_derived
        call c_derived_matrix_int_set_derived(obj%cxxmem, v)
        ! splicer end class.DerivedMatrix_int.method.set_derived
    end subroutine derived_matrix_int_set_derived

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  int get_derived
    ! Statement: f_function_native
    function derived_matrix_int_get_derived(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT
        class(derived_matrix_int), intent(INOUT) :: obj
        integer(C_INT) :: SHT_rv
        ! splicer begin class.DerivedMatrix_int.method.get_derived
        SHT_rv = c_derived_matrix_int_get_derived(obj%cxxmem)
        ! splicer end class.DerivedMatrix_int.method.get_derived
    end function derived_matrix_int_get_derived

    ! splicer begin class.DerivedMatrix_int.additional_functions
    ! splicer end class.DerivedMatrix_int.additional_functions

    ! ----------------------------------------
    ! Function:  DerivedMatrix
    ! Statement: f_ctor_shadow_capsule_caller
    function derived_matrix_double_ctor() &
            result(SHT_rv)
        type(derived_matrix_double) :: SHT_rv
        ! splicer begin class.DerivedMatrix_double.method.ctor
        call c_derived_matrix_double_ctor_bufferify(SHT_rv%cxxmem)
        ! splicer end class.DerivedMatrix_double.method.ctor
    end function derived_matrix_double_ctor

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void set_derived
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  double v
    ! Statement: f_in_native
    subroutine derived_matrix_double_set_derived(obj, v)
        use iso_c_binding, only : C_DOUBLE
        class(derived_matrix_double), intent(INOUT) :: obj
        real(C_DOUBLE), value, intent(IN) :: v
        ! splicer begin class.DerivedMatrix_double.method.set_derived
        call c_derived_matrix_double_set_derived(obj%cxxmem, v)
        ! splicer end class.DerivedMatrix_double.method.set_derived
    end subroutine derived_matrix_double_set_derived

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  double get_derived
    ! Statement: f_function_native
    function derived_matrix_double_get_derived(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_DOUBLE
        class(derived_matrix_double), intent(INOUT) :: obj
        real(C_DOUBLE) :: SHT_rv
        ! splicer begin class.DerivedMatrix_double.method.get_derived
        SHT_rv = c_derived_matrix_double_get_derived(obj%cxxmem)
        ! splicer end class.DerivedMatrix_double.method.get_derived
    end function derived_matrix_double_get_derived

    ! splicer begin class.DerivedMatrix_double.additional_functions
    ! splicer end class.DerivedMatrix_double.additional_functions

    ! ----------------------------------------
    ! Function:  MixedMatrix
    ! Statement: f_ctor_shadow_capsule_caller
    function mixed_matrix_int_double_ctor() &
            result(SHT_rv)
        type(mixed_matrix_int_double) :: SHT_rv
        ! splicer begin class.MixedMatrix_int_double.method.ctor
        call c_mixed_matrix_int_double_ctor_bufferify(SHT_rv%cxxmem)
        ! splicer end class.MixedMatrix_int_double.method.ctor
    end function mixed_matrix_int_double_ctor

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  double get_mixed
    ! Statement: f_function_native
    function mixed_matrix_int_double_get_mixed(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_DOUBLE
        class(mixed_matrix_int_double), intent(INOUT) :: obj
        real(C_DOUBLE) :: SHT_rv
        ! splicer begin class.MixedMatrix_int_double.method.get_mixed
        SHT_rv = c_mixed_matrix_int_double_get_mixed(obj%cxxmem)
        ! splicer end class.MixedMatrix_int_double.method.get_mixed
    end function mixed_matrix_int_double_get_mixed

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void convert
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  int value
    ! Statement: f_in_native
    subroutine mixed_matrix_int_double_convert_int(obj, value)
        use iso_c_binding, only : C_INT
        class(mixed_matrix_int_double), intent(INOUT) :: obj
        integer(C_INT), value, intent(IN) :: value
        ! splicer begin class.MixedMatrix_int_double.method.convert_int
        call c_mixed_matrix_int_double_convert_int(obj%cxxmem, value)
        ! splicer end class.MixedMatrix_int_double.method.convert_int
    end subroutine mixed_matrix_int_double_convert_int

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void convert
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  double value
    ! Statement: f_in_native
    subroutine mixed_matrix_int_double_convert_double(obj, value)
        use iso_c_binding, only : C_DOUBLE
        class(mixed_matrix_int_double), intent(INOUT) :: obj
        real(C_DOUBLE), value, intent(IN) :: value
        ! splicer begin class.MixedMatrix_int_double.method.convert_double
        call c_mixed_matrix_int_double_convert_double(obj%cxxmem, value)
        ! splicer end class.MixedMatrix_int_double.method.convert_double
    end subroutine mixed_matrix_int_double_convert_double

    ! splicer begin class.MixedMatrix_int_double.additional_functions
    ! splicer end class.MixedMatrix_int_double.additional_functions

    ! ----------------------------------------
    ! Function:  MixedMatrix
    ! Statement: f_ctor_shadow_capsule_caller
    function mixed_matrix_double_int_ctor() &
            result(SHT_rv)
        type(mixed_matrix_double_int) :: SHT_rv
        ! splicer begin class.MixedMatrix_double_int.method.ctor
        call c_mixed_matrix_double_int_ctor_bufferify(SHT_rv%cxxmem)
        ! splicer end class.MixedMatrix_double_int.method.ctor
    end function mixed_matrix_double_int_ctor

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void set_mixed
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  double v
    ! Statement: f_in_native
    ! ----------------------------------------
    ! Argument:  int w
    ! Statement: f_in_native
    subroutine mixed_matrix_double_int_set_mixed(obj, v, w)
        use iso_c_binding, only : C_DOUBLE, C_INT
        class(mixed_matrix_double_int), intent(INOUT) :: obj
        real(C_DOUBLE), value, intent(IN) :: v
        integer(C_INT), value, intent(IN) :: w
        ! splicer begin class.MixedMatrix_double_int.method.set_mixed
        call c_mixed_matrix_double_int_set_mixed(obj%cxxmem, v, w)
        ! splicer end class.MixedMatrix_double_int.method.set_mixed
    end subroutine mixed_matrix_double_int_set_mixed

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  int get_mixed
    ! Statement: f_function_native
    function mixed_matrix_double_int_get_mixed(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT
        class(mixed_matrix_double_int), intent(INOUT) :: obj
        integer(C_INT) :: SHT_rv
        ! splicer begin class.MixedMatrix_double_int.method.get_mixed
        SHT_rv = c_mixed_matrix_double_int_get_mixed(obj%cxxmem)
        ! splicer end class.MixedMatrix_double_int.method.get_mixed
    end function mixed_matrix_double_int_get_mixed

    ! splicer begin class.MixedMatrix_double_int.additional_functions
    ! splicer end class.MixedMatrix_double_int.additional_functions

    ! ----------------------------------------
    ! Function:  ConcreteMatrix
    ! Statement: f_ctor_shadow_capsule_caller
    function concrete_matrix_int_ctor() &
            result(SHT_rv)
        type(concrete_matrix_int) :: SHT_rv
        ! splicer begin class.ConcreteMatrix_int.method.ctor
        call c_concrete_matrix_int_ctor_bufferify(SHT_rv%cxxmem)
        ! splicer end class.ConcreteMatrix_int.method.ctor
    end function concrete_matrix_int_ctor

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void set_concrete
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  int v
    ! Statement: f_in_native
    subroutine concrete_matrix_int_set_concrete(obj, v)
        use iso_c_binding, only : C_INT
        class(concrete_matrix_int), intent(INOUT) :: obj
        integer(C_INT), value, intent(IN) :: v
        ! splicer begin class.ConcreteMatrix_int.method.set_concrete
        call c_concrete_matrix_int_set_concrete(obj%cxxmem, v)
        ! splicer end class.ConcreteMatrix_int.method.set_concrete
    end subroutine concrete_matrix_int_set_concrete

    ! splicer begin class.ConcreteMatrix_int.additional_functions
    ! splicer end class.ConcreteMatrix_int.additional_functions

    ! ----------------------------------------
    ! Function:  ConcreteMatrix
    ! Statement: f_ctor_shadow_capsule_caller
    function concrete_matrix_double_ctor() &
            result(SHT_rv)
        type(concrete_matrix_double) :: SHT_rv
        ! splicer begin class.ConcreteMatrix_double.method.ctor
        call c_concrete_matrix_double_ctor_bufferify(SHT_rv%cxxmem)
        ! splicer end class.ConcreteMatrix_double.method.ctor
    end function concrete_matrix_double_ctor

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void set_concrete
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  double v
    ! Statement: f_in_native
    subroutine concrete_matrix_double_set_concrete(obj, v)
        use iso_c_binding, only : C_DOUBLE
        class(concrete_matrix_double), intent(INOUT) :: obj
        real(C_DOUBLE), value, intent(IN) :: v
        ! splicer begin class.ConcreteMatrix_double.method.set_concrete
        call c_concrete_matrix_double_set_concrete(obj%cxxmem, v)
        ! splicer end class.ConcreteMatrix_double.method.set_concrete
    end subroutine concrete_matrix_double_set_concrete

    ! splicer begin class.ConcreteMatrix_double.additional_functions
    ! splicer end class.ConcreteMatrix_double.additional_functions

    ! Statement: f_operator_assignment_shadow
    ! BaseMatrix_int = BaseMatrix_int
    subroutine base_matrix_int_assign_BaseMatrix_int(lhs, rhs)
        use iso_c_binding, only : c_associated, c_f_pointer
        class(base_matrix_int), intent(INOUT) :: lhs
        type(base_matrix_int), intent(IN) :: rhs
        interface
            subroutine do_assign(lhs, rhs) bind(C, &
                name="TEM_BaseMatrix_int_assign_BaseMatrix_int")
                import :: TEM_SHROUD_capsule_data
                type(TEM_SHROUD_capsule_data), intent(INOUT) :: lhs
                type(TEM_SHROUD_capsule_data), intent(IN) :: rhs
            end subroutine do_assign
        end interface
        call do_assign(lhs%cxxmem, rhs%cxxmem)
    end subroutine base_matrix_int_assign_BaseMatrix_int

    ! Statement: f_operator_assignment_shadow
    ! BaseMatrix_double = BaseMatrix_double
    subroutine base_matrix_double_assign_BaseMatrix_double(lhs, rhs)
        use iso_c_binding, only : c_associated, c_f_pointer
        class(base_matrix_double), intent(INOUT) :: lhs
        type(base_matrix_double), intent(IN) :: rhs
        interface
            subroutine do_assign(lhs, rhs) bind(C, &
                name="TEM_BaseMatrix_double_assign_BaseMatrix_double")
                import :: TEM_SHROUD_capsule_data
                type(TEM_SHROUD_capsule_data), intent(INOUT) :: lhs
                type(TEM_SHROUD_capsule_data), intent(IN) :: rhs
            end subroutine do_assign
        end interface
        call do_assign(lhs%cxxmem, rhs%cxxmem)
    end subroutine base_matrix_double_assign_BaseMatrix_double

    ! Statement: f_operator_assignment_shadow
    ! DerivedMatrix_int = DerivedMatrix_int
    subroutine derived_matrix_int_assign_DerivedMatrix_int(lhs, rhs)
        use iso_c_binding, only : c_associated, c_f_pointer
        class(derived_matrix_int), intent(INOUT) :: lhs
        type(derived_matrix_int), intent(IN) :: rhs
        interface
            subroutine do_assign(lhs, rhs) bind(C, &
                name="TEM_DerivedMatrix_int_assign_DerivedMatrix_int")
                import :: TEM_SHROUD_capsule_data
                type(TEM_SHROUD_capsule_data), intent(INOUT) :: lhs
                type(TEM_SHROUD_capsule_data), intent(IN) :: rhs
            end subroutine do_assign
        end interface
        call do_assign(lhs%cxxmem, rhs%cxxmem)
    end subroutine derived_matrix_int_assign_DerivedMatrix_int

    ! Statement: f_operator_assignment_shadow
    ! DerivedMatrix_double = DerivedMatrix_double
    subroutine derived_matrix_double_assign_DerivedMatrix_double(lhs, rhs)
        use iso_c_binding, only : c_associated, c_f_pointer
        class(derived_matrix_double), intent(INOUT) :: lhs
        type(derived_matrix_double), intent(IN) :: rhs
        interface
            subroutine do_assign(lhs, rhs) bind(C, &
                name="TEM_DerivedMatrix_double_assign_DerivedMatrix_double")
                import :: TEM_SHROUD_capsule_data
                type(TEM_SHROUD_capsule_data), intent(INOUT) :: lhs
                type(TEM_SHROUD_capsule_data), intent(IN) :: rhs
            end subroutine do_assign
        end interface
        call do_assign(lhs%cxxmem, rhs%cxxmem)
    end subroutine derived_matrix_double_assign_DerivedMatrix_double

    ! Statement: f_operator_assignment_shadow
    ! MixedMatrix_int_double = MixedMatrix_int_double
    subroutine mixed_matrix_int_double_assign_MixedMatrix_int_double(lhs, rhs)
        use iso_c_binding, only : c_associated, c_f_pointer
        class(mixed_matrix_int_double), intent(INOUT) :: lhs
        type(mixed_matrix_int_double), intent(IN) :: rhs
        interface
            subroutine do_assign(lhs, rhs) bind(C, &
                name="TEM_MixedMatrix_int_double_assign_MixedMatrix_int_double")
                import :: TEM_SHROUD_capsule_data
                type(TEM_SHROUD_capsule_data), intent(INOUT) :: lhs
                type(TEM_SHROUD_capsule_data), intent(IN) :: rhs
            end subroutine do_assign
        end interface
        call do_assign(lhs%cxxmem, rhs%cxxmem)
    end subroutine mixed_matrix_int_double_assign_MixedMatrix_int_double

    ! Statement: f_operator_assignment_shadow
    ! MixedMatrix_double_int = MixedMatrix_double_int
    subroutine mixed_matrix_double_int_assign_MixedMatrix_double_int(lhs, rhs)
        use iso_c_binding, only : c_associated, c_f_pointer
        class(mixed_matrix_double_int), intent(INOUT) :: lhs
        type(mixed_matrix_double_int), intent(IN) :: rhs
        interface
            subroutine do_assign(lhs, rhs) bind(C, &
                name="TEM_MixedMatrix_double_int_assign_MixedMatrix_double_int")
                import :: TEM_SHROUD_capsule_data
                type(TEM_SHROUD_capsule_data), intent(INOUT) :: lhs
                type(TEM_SHROUD_capsule_data), intent(IN) :: rhs
            end subroutine do_assign
        end interface
        call do_assign(lhs%cxxmem, rhs%cxxmem)
    end subroutine mixed_matrix_double_int_assign_MixedMatrix_double_int

    ! Statement: f_operator_assignment_shadow
    ! ConcreteMatrix_int = ConcreteMatrix_int
    subroutine concrete_matrix_int_assign_ConcreteMatrix_int(lhs, rhs)
        use iso_c_binding, only : c_associated, c_f_pointer
        class(concrete_matrix_int), intent(INOUT) :: lhs
        type(concrete_matrix_int), intent(IN) :: rhs
        interface
            subroutine do_assign(lhs, rhs) bind(C, &
                name="TEM_ConcreteMatrix_int_assign_ConcreteMatrix_int")
                import :: TEM_SHROUD_capsule_data
                type(TEM_SHROUD_capsule_data), intent(INOUT) :: lhs
                type(TEM_SHROUD_capsule_data), intent(IN) :: rhs
            end subroutine do_assign
        end interface
        call do_assign(lhs%cxxmem, rhs%cxxmem)
    end subroutine concrete_matrix_int_assign_ConcreteMatrix_int

    ! Statement: f_operator_assignment_shadow
    ! ConcreteMatrix_double = ConcreteMatrix_double
    subroutine concrete_matrix_double_assign_ConcreteMatrix_double(lhs, rhs)
        use iso_c_binding, only : c_associated, c_f_pointer
        class(concrete_matrix_double), intent(INOUT) :: lhs
        type(concrete_matrix_double), intent(IN) :: rhs
        interface
            subroutine do_assign(lhs, rhs) bind(C, &
                name="TEM_ConcreteMatrix_double_assign_ConcreteMatrix_double")
                import :: TEM_SHROUD_capsule_data
                type(TEM_SHROUD_capsule_data), intent(INOUT) :: lhs
                type(TEM_SHROUD_capsule_data), intent(IN) :: rhs
            end subroutine do_assign
        end interface
        call do_assign(lhs%cxxmem, rhs%cxxmem)
    end subroutine concrete_matrix_double_assign_ConcreteMatrix_double

    ! splicer begin additional_functions
    ! splicer end additional_functions

    function base_matrix_int_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(base_matrix_int), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function base_matrix_int_eq

    function base_matrix_int_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(base_matrix_int), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function base_matrix_int_ne

    function base_matrix_double_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(base_matrix_double), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function base_matrix_double_eq

    function base_matrix_double_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(base_matrix_double), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function base_matrix_double_ne

    function derived_matrix_int_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(derived_matrix_int), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function derived_matrix_int_eq

    function derived_matrix_int_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(derived_matrix_int), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function derived_matrix_int_ne

    function derived_matrix_double_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(derived_matrix_double), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function derived_matrix_double_eq

    function derived_matrix_double_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(derived_matrix_double), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function derived_matrix_double_ne

    function mixed_matrix_int_double_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(mixed_matrix_int_double), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function mixed_matrix_int_double_eq

    function mixed_matrix_int_double_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(mixed_matrix_int_double), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function mixed_matrix_int_double_ne

    function mixed_matrix_double_int_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(mixed_matrix_double_int), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function mixed_matrix_double_int_eq

    function mixed_matrix_double_int_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(mixed_matrix_double_int), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function mixed_matrix_double_int_ne

    function concrete_matrix_int_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(concrete_matrix_int), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function concrete_matrix_int_eq

    function concrete_matrix_int_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(concrete_matrix_int), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function concrete_matrix_int_ne

    function concrete_matrix_double_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(concrete_matrix_double), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function concrete_matrix_double_eq

    function concrete_matrix_double_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(concrete_matrix_double), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function concrete_matrix_double_ne

end module templateinherit_mod
