// wrapMixedMatrix_double_int.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapMixedMatrix_double_int.h
 * \brief Shroud generated wrapper for MixedMatrix class
 */
// For C users and C++ implementation

#ifndef WRAPMIXEDMATRIX_DOUBLE_INT_H
#define WRAPMIXEDMATRIX_DOUBLE_INT_H

// shroud
#include "typestemplateinherit.h"

// splicer begin class.MixedMatrix.CXX_declarations
// splicer end class.MixedMatrix.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.MixedMatrix.C_declarations
// splicer end class.MixedMatrix.C_declarations

TEM_MixedMatrix_double_int * TEM_MixedMatrix_double_int_ctor(
    TEM_MixedMatrix_double_int *SHC_rv);

void TEM_MixedMatrix_double_int_ctor_bufferify(
    TEM_MixedMatrix_double_int *SHC_rv);

void TEM_MixedMatrix_double_int_set_mixed(
    TEM_MixedMatrix_double_int * self, double v, int w);

int TEM_MixedMatrix_double_int_get_mixed(
    TEM_MixedMatrix_double_int * self);

#ifdef __cplusplus
}
#endif

#endif  // WRAPMIXEDMATRIX_DOUBLE_INT_H
