// wrapBaseMatrix_double.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// cxx_header
#include "templateinherit.hpp"
// shroud
#include "wrapBaseMatrix_double.h"

// splicer begin class.BaseMatrix.CXX_definitions
// splicer end class.BaseMatrix.CXX_definitions

extern "C" {

// splicer begin class.BaseMatrix.C_definitions
// splicer end class.BaseMatrix.C_definitions

// ----------------------------------------
// Function:  BaseMatrix
// Statement: c_ctor_shadow_capptr
TEM_BaseMatrix_double * TEM_BaseMatrix_double_ctor(
    TEM_BaseMatrix_double *SHC_rv)
{
    // splicer begin class.BaseMatrix.method.ctor
    BaseMatrix<double> *SHCXX_rv = new BaseMatrix<double>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 2;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    return SHC_rv;
    // splicer end class.BaseMatrix.method.ctor
}

// ----------------------------------------
// Function:  BaseMatrix
// Statement: f_ctor_shadow_capsule_caller
void TEM_BaseMatrix_double_ctor_bufferify(TEM_BaseMatrix_double *SHC_rv)
{
    // splicer begin class.BaseMatrix.method.ctor_bufferify
    BaseMatrix<double> *SHCXX_rv = new BaseMatrix<double>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 2;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    // splicer end class.BaseMatrix.method.ctor_bufferify
}

// Generated by cxx_template
// ----------------------------------------
// Function:  void set_base
// Statement: c_subroutine
// ----------------------------------------
// Argument:  double v
// Statement: c_in_native
void TEM_BaseMatrix_double_set_base(TEM_BaseMatrix_double * self,
    double v)
{
    BaseMatrix<double> *SH_this = static_cast<BaseMatrix<double> *>
        (self->addr);
    // splicer begin class.BaseMatrix.method.set_base
    SH_this->set_base(v);
    // splicer end class.BaseMatrix.method.set_base
}

// Generated by cxx_template
// ----------------------------------------
// Function:  double get_base
// Statement: c_function_native
double TEM_BaseMatrix_double_get_base(TEM_BaseMatrix_double * self)
{
    BaseMatrix<double> *SH_this = static_cast<BaseMatrix<double> *>
        (self->addr);
    // splicer begin class.BaseMatrix.method.get_base
    double SHC_rv = SH_this->get_base();
    return SHC_rv;
    // splicer end class.BaseMatrix.method.get_base
}

}  // extern "C"
