// wrapDerivedMatrix_int.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapDerivedMatrix_int.h
 * \brief Shroud generated wrapper for DerivedMatrix class
 */
// For C users and C++ implementation

#ifndef WRAPDERIVEDMATRIX_INT_H
#define WRAPDERIVEDMATRIX_INT_H

// shroud
#include "typestemplateinherit.h"

// splicer begin class.DerivedMatrix.CXX_declarations
// splicer end class.DerivedMatrix.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.DerivedMatrix.C_declarations
// splicer end class.DerivedMatrix.C_declarations

TEM_DerivedMatrix_int * TEM_DerivedMatrix_int_ctor(
    TEM_DerivedMatrix_int *SHC_rv);

void TEM_DerivedMatrix_int_ctor_bufferify(
    TEM_DerivedMatrix_int *SHC_rv);

void TEM_DerivedMatrix_int_set_derived(TEM_DerivedMatrix_int * self,
    int v);

int TEM_DerivedMatrix_int_get_derived(TEM_DerivedMatrix_int * self);

#ifdef __cplusplus
}
#endif

#endif  // WRAPDERIVEDMATRIX_INT_H
