// wrapConcreteMatrix_int.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// cxx_header
#include "templateinherit.hpp"
// shroud
#include "wrapConcreteMatrix_int.h"

// splicer begin class.ConcreteMatrix.CXX_definitions
// splicer end class.ConcreteMatrix.CXX_definitions

extern "C" {

// splicer begin class.ConcreteMatrix.C_definitions
// splicer end class.ConcreteMatrix.C_definitions

// ----------------------------------------
// Function:  ConcreteMatrix
// Statement: c_ctor_shadow_capptr
TEM_ConcreteMatrix_int * TEM_ConcreteMatrix_int_ctor(
    TEM_ConcreteMatrix_int *SHC_rv)
{
    // splicer begin class.ConcreteMatrix.method.ctor
    ConcreteMatrix<int> *SHCXX_rv = new ConcreteMatrix<int>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 7;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    return SHC_rv;
    // splicer end class.ConcreteMatrix.method.ctor
}

// ----------------------------------------
// Function:  ConcreteMatrix
// Statement: f_ctor_shadow_capsule_caller
void TEM_ConcreteMatrix_int_ctor_bufferify(
    TEM_ConcreteMatrix_int *SHC_rv)
{
    // splicer begin class.ConcreteMatrix.method.ctor_bufferify
    ConcreteMatrix<int> *SHCXX_rv = new ConcreteMatrix<int>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 7;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    // splicer end class.ConcreteMatrix.method.ctor_bufferify
}

// Generated by cxx_template
// ----------------------------------------
// Function:  void set_concrete
// Statement: c_subroutine
// ----------------------------------------
// Argument:  int v
// Statement: c_in_native
void TEM_ConcreteMatrix_int_set_concrete(TEM_ConcreteMatrix_int * self,
    int v)
{
    ConcreteMatrix<int> *SH_this = static_cast<ConcreteMatrix<int> *>
        (self->addr);
    // splicer begin class.ConcreteMatrix.method.set_concrete
    SH_this->set_concrete(v);
    // splicer end class.ConcreteMatrix.method.set_concrete
}

}  // extern "C"
