// wrapDerivedMatrix_double.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapDerivedMatrix_double.h
 * \brief Shroud generated wrapper for DerivedMatrix class
 */
// For C users and C++ implementation

#ifndef WRAPDERIVEDMATRIX_DOUBLE_H
#define WRAPDERIVEDMATRIX_DOUBLE_H

// shroud
#include "typestemplateinherit.h"

// splicer begin class.DerivedMatrix.CXX_declarations
// splicer end class.DerivedMatrix.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.DerivedMatrix.C_declarations
// splicer end class.DerivedMatrix.C_declarations

TEM_DerivedMatrix_double * TEM_DerivedMatrix_double_ctor(
    TEM_DerivedMatrix_double *SHC_rv);

void TEM_DerivedMatrix_double_ctor_bufferify(
    TEM_DerivedMatrix_double *SHC_rv);

void TEM_DerivedMatrix_double_set_derived(
    TEM_DerivedMatrix_double * self, double v);

double TEM_DerivedMatrix_double_get_derived(
    TEM_DerivedMatrix_double * self);

#ifdef __cplusplus
}
#endif

#endif  // WRAPDERIVEDMATRIX_DOUBLE_H
