// wrapBaseMatrix_double.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapBaseMatrix_double.h
 * \brief Shroud generated wrapper for BaseMatrix class
 */
// For C users and C++ implementation

#ifndef WRAPBASEMATRIX_DOUBLE_H
#define WRAPBASEMATRIX_DOUBLE_H

// shroud
#include "typestemplateinherit.h"

// splicer begin class.BaseMatrix.CXX_declarations
// splicer end class.BaseMatrix.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.BaseMatrix.C_declarations
// splicer end class.BaseMatrix.C_declarations

TEM_BaseMatrix_double * TEM_BaseMatrix_double_ctor(
    TEM_BaseMatrix_double *SHC_rv);

void TEM_BaseMatrix_double_ctor_bufferify(
    TEM_BaseMatrix_double *SHC_rv);

void TEM_BaseMatrix_double_set_base(TEM_BaseMatrix_double * self,
    double v);

double TEM_BaseMatrix_double_get_base(TEM_BaseMatrix_double * self);

#ifdef __cplusplus
}
#endif

#endif  // WRAPBASEMATRIX_DOUBLE_H
