// wrapMixedMatrix_int_double.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// cxx_header
#include "templateinherit.hpp"
// shroud
#include "wrapMixedMatrix_int_double.h"

// splicer begin class.MixedMatrix.CXX_definitions
// splicer end class.MixedMatrix.CXX_definitions

extern "C" {

// splicer begin class.MixedMatrix.C_definitions
// splicer end class.MixedMatrix.C_definitions

// ----------------------------------------
// Function:  MixedMatrix
// Statement: c_ctor_shadow_capptr
TEM_MixedMatrix_int_double * TEM_MixedMatrix_int_double_ctor(
    TEM_MixedMatrix_int_double *SHC_rv)
{
    // splicer begin class.MixedMatrix.method.ctor
    MixedMatrix<int, double> *SHCXX_rv = new MixedMatrix<int, double>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 5;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    return SHC_rv;
    // splicer end class.MixedMatrix.method.ctor
}

// ----------------------------------------
// Function:  MixedMatrix
// Statement: f_ctor_shadow_capsule_caller
void TEM_MixedMatrix_int_double_ctor_bufferify(
    TEM_MixedMatrix_int_double *SHC_rv)
{
    // splicer begin class.MixedMatrix.method.ctor_bufferify
    MixedMatrix<int, double> *SHCXX_rv = new MixedMatrix<int, double>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 5;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    // splicer end class.MixedMatrix.method.ctor_bufferify
}

// Generated by cxx_template
// ----------------------------------------
// Function:  double get_mixed
// Statement: c_function_native
double TEM_MixedMatrix_int_double_get_mixed(
    TEM_MixedMatrix_int_double * self)
{
    MixedMatrix<int, double> *SH_this =
        static_cast<MixedMatrix<int, double> *>(self->addr);
    // splicer begin class.MixedMatrix.method.get_mixed
    double SHC_rv = SH_this->get_mixed();
    return SHC_rv;
    // splicer end class.MixedMatrix.method.get_mixed
}

// Generated by cxx_template
// ----------------------------------------
// Function:  void convert
// Statement: c_subroutine
// ----------------------------------------
// Argument:  int value
// Statement: c_in_native
void TEM_MixedMatrix_int_double_convert_int(
    TEM_MixedMatrix_int_double * self, int value)
{
    MixedMatrix<int, double> *SH_this =
        static_cast<MixedMatrix<int, double> *>(self->addr);
    // splicer begin class.MixedMatrix.method.convert_int
    SH_this->convert<int>(value);
    // splicer end class.MixedMatrix.method.convert_int
}

// Generated by cxx_template
// ----------------------------------------
// Function:  void convert
// Statement: c_subroutine
// ----------------------------------------
// Argument:  double value
// Statement: c_in_native
void TEM_MixedMatrix_int_double_convert_double(
    TEM_MixedMatrix_int_double * self, double value)
{
    MixedMatrix<int, double> *SH_this =
        static_cast<MixedMatrix<int, double> *>(self->addr);
    // splicer begin class.MixedMatrix.method.convert_double
    SH_this->convert<double>(value);
    // splicer end class.MixedMatrix.method.convert_double
}

}  // extern "C"
