// wrapConcreteMatrix_double.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapConcreteMatrix_double.h
 * \brief Shroud generated wrapper for ConcreteMatrix class
 */
// For C users and C++ implementation

#ifndef WRAPCONCRETEMATRIX_DOUBLE_H
#define WRAPCONCRETEMATRIX_DOUBLE_H

// shroud
#include "typestemplateinherit.h"

// splicer begin class.ConcreteMatrix.CXX_declarations
// splicer end class.ConcreteMatrix.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.ConcreteMatrix.C_declarations
// splicer end class.ConcreteMatrix.C_declarations

TEM_ConcreteMatrix_double * TEM_ConcreteMatrix_double_ctor(
    TEM_ConcreteMatrix_double *SHC_rv);

void TEM_ConcreteMatrix_double_ctor_bufferify(
    TEM_ConcreteMatrix_double *SHC_rv);

void TEM_ConcreteMatrix_double_set_concrete(
    TEM_ConcreteMatrix_double * self, double v);

#ifdef __cplusplus
}
#endif

#endif  // WRAPCONCRETEMATRIX_DOUBLE_H
