// wrapDerivedMatrix_double.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// cxx_header
#include "templateinherit.hpp"
// shroud
#include "wrapDerivedMatrix_double.h"

// splicer begin class.DerivedMatrix.CXX_definitions
// splicer end class.DerivedMatrix.CXX_definitions

extern "C" {

// splicer begin class.DerivedMatrix.C_definitions
// splicer end class.DerivedMatrix.C_definitions

// ----------------------------------------
// Function:  DerivedMatrix
// Statement: c_ctor_shadow_capptr
TEM_DerivedMatrix_double * TEM_DerivedMatrix_double_ctor(
    TEM_DerivedMatrix_double *SHC_rv)
{
    // splicer begin class.DerivedMatrix.method.ctor
    DerivedMatrix<double> *SHCXX_rv = new DerivedMatrix<double>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 4;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    return SHC_rv;
    // splicer end class.DerivedMatrix.method.ctor
}

// ----------------------------------------
// Function:  DerivedMatrix
// Statement: f_ctor_shadow_capsule_caller
void TEM_DerivedMatrix_double_ctor_bufferify(
    TEM_DerivedMatrix_double *SHC_rv)
{
    // splicer begin class.DerivedMatrix.method.ctor_bufferify
    DerivedMatrix<double> *SHCXX_rv = new DerivedMatrix<double>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 4;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    // splicer end class.DerivedMatrix.method.ctor_bufferify
}

// Generated by cxx_template
// ----------------------------------------
// Function:  void set_derived
// Statement: c_subroutine
// ----------------------------------------
// Argument:  double v
// Statement: c_in_native
void TEM_DerivedMatrix_double_set_derived(
    TEM_DerivedMatrix_double * self, double v)
{
    DerivedMatrix<double> *SH_this =
        static_cast<DerivedMatrix<double> *>(self->addr);
    // splicer begin class.DerivedMatrix.method.set_derived
    SH_this->set_derived(v);
    // splicer end class.DerivedMatrix.method.set_derived
}

// Generated by cxx_template
// ----------------------------------------
// Function:  double get_derived
// Statement: c_function_native
double TEM_DerivedMatrix_double_get_derived(
    TEM_DerivedMatrix_double * self)
{
    DerivedMatrix<double> *SH_this =
        static_cast<DerivedMatrix<double> *>(self->addr);
    // splicer begin class.DerivedMatrix.method.get_derived
    double SHC_rv = SH_this->get_derived();
    return SHC_rv;
    // splicer end class.DerivedMatrix.method.get_derived
}

}  // extern "C"
