// wrapDerivedMatrix_int.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// cxx_header
#include "templateinherit.hpp"
// shroud
#include "wrapDerivedMatrix_int.h"

// splicer begin class.DerivedMatrix.CXX_definitions
// splicer end class.DerivedMatrix.CXX_definitions

extern "C" {

// splicer begin class.DerivedMatrix.C_definitions
// splicer end class.DerivedMatrix.C_definitions

// ----------------------------------------
// Function:  DerivedMatrix
// Statement: c_ctor_shadow_capptr
TEM_DerivedMatrix_int * TEM_DerivedMatrix_int_ctor(
    TEM_DerivedMatrix_int *SHC_rv)
{
    // splicer begin class.DerivedMatrix.method.ctor
    DerivedMatrix<int> *SHCXX_rv = new DerivedMatrix<int>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 3;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    return SHC_rv;
    // splicer end class.DerivedMatrix.method.ctor
}

// ----------------------------------------
// Function:  DerivedMatrix
// Statement: f_ctor_shadow_capsule_caller
void TEM_DerivedMatrix_int_ctor_bufferify(TEM_DerivedMatrix_int *SHC_rv)
{
    // splicer begin class.DerivedMatrix.method.ctor_bufferify
    DerivedMatrix<int> *SHCXX_rv = new DerivedMatrix<int>();
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 3;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    // splicer end class.DerivedMatrix.method.ctor_bufferify
}

// Generated by cxx_template
// ----------------------------------------
// Function:  void set_derived
// Statement: c_subroutine
// ----------------------------------------
// Argument:  int v
// Statement: c_in_native
void TEM_DerivedMatrix_int_set_derived(TEM_DerivedMatrix_int * self,
    int v)
{
    DerivedMatrix<int> *SH_this = static_cast<DerivedMatrix<int> *>
        (self->addr);
    // splicer begin class.DerivedMatrix.method.set_derived
    SH_this->set_derived(v);
    // splicer end class.DerivedMatrix.method.set_derived
}

// Generated by cxx_template
// ----------------------------------------
// Function:  int get_derived
// Statement: c_function_native
int TEM_DerivedMatrix_int_get_derived(TEM_DerivedMatrix_int * self)
{
    DerivedMatrix<int> *SH_this = static_cast<DerivedMatrix<int> *>
        (self->addr);
    // splicer begin class.DerivedMatrix.method.get_derived
    int SHC_rv = SH_this->get_derived();
    return SHC_rv;
    // splicer end class.DerivedMatrix.method.get_derived
}

}  // extern "C"
